ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION MDL_MW,MDL_MZP,MDL_MCHI1,MDL_MCHI2,MDL_MH
     $ ,MDL_MTA,MDL_MZ,MDL_ME,MDL_MHS,MDL_MM,MDL_MC,MDL_MT,MDL_MB

      COMMON/MASSES/ MDL_MW,MDL_MZP,MDL_MCHI1,MDL_MCHI2,MDL_MH,MDL_MTA
     $ ,MDL_MZ,MDL_ME,MDL_MHS,MDL_MM,MDL_MC,MDL_MT,MDL_MB


      DOUBLE PRECISION MDL_WZ,MDL_WCHI2,MDL_WT,MDL_WW,MDL_WH,MDL_WZP
     $ ,MDL_WHS

      COMMON/WIDTHS/ MDL_WZ,MDL_WCHI2,MDL_WT,MDL_WW,MDL_WH,MDL_WZP
     $ ,MDL_WHS


      DOUBLE COMPLEX GC_6, GC_36, GC_38, GC_39, GC_45, GC_47, GC_48,
     $  GC_14, GC_17

      COMMON/COUPLINGS/ GC_6, GC_36, GC_38, GC_39, GC_45, GC_47, GC_48
     $ , GC_14, GC_17

